project_top_level: /SAN/vyplab/alb_projects/data/4su_better_design_ward_ipsc
fastp_trimmed_output_folder: 4SU_second_experiment_i3cort/fastp_trimmed/
merged_fastq_folder: 4SU_second_experiment_i3cort/merged_trimmed/
sampleCSVpath: /SAN/vyplab/alb_projects/data/4su_better_design_ward_ipsc/foursu_full_experiment.csv
fastp_path: /SAN/vyplab/alb_projects/tools/fastp

end_type: pe
