# a top level folder where the bams reside
project_dir: "/home/annbrown/data/ursa_mouse"
out_spot: "name_sortbams/"
bam_spot: "ori_bams/"
fastq_spot: "pulled_fastq/"

bam_suffix: ".bam"
end_type: "pe"