# Directory containing input BAMs from which to extract FASTQs
input_dir: /SAN/vyplab/alb_projects/data/tdp_ko_collection/all_bams_sym/
bam_suffix: ".Aligned.sorted.out.bam"

# Directory to store temporary name-sorted BAM files
temp_dir: /SAN/vyplab/alb_projects/data/tdp_ko_collection/temp_name_sort_dir/

# Where to output pulled FASTQs
fastq_spot: /SAN/vyplab/alb_projects/data/tdp_ko_collection/pulled_fastq/

# 'pe' for paired-end, 'se' for single-end
end_type: "pe"

# Number of extra threads to use for samtools collate
collate_extra_threads: 0
# Number of extra threads to use for samtools fastq
fastq_extra_threads: 0
